title: 'Crystal Jewelry'
content: 'Ali’s handmade, wrapped crystal jewlery takes advantage of the natural healing properties of the crystals to give you constant access to their benefits.'
updated_by: 077f4893-39f2-4e88-a75b-5fa35b145ff0
updated_at: 1614058036
blueprint: product_categories
