title: 'The Essentials'
content: 'The Spirituali Essentials include our vast collection of essential oils, dried herbs, and so much more.'
updated_by: 077f4893-39f2-4e88-a75b-5fa35b145ff0
updated_at: 1614716754
blueprint: product_categories
